#!/usr/bin/env bash
# Regenerate the Gantt viewer for this schedule. Rerun after editing the
# schedule YAML. Generated by `uv run compute`; overwritten on each compute.
# Safe to delete.
set -euo pipefail
proj="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
skill="$HOME/.aschneer/skills/personal_skills/schedule"
( cd "$skill" && uv run compute --no-serve "$proj/{schedule_filename}" )
