#!/usr/bin/env bash
# Recompute the Gantt viewer for this schedule and serve it in a browser.
# Rerun after editing the schedule YAML. Runs `compute` (which serves at the
# end), so it blocks until you stop it with Ctrl+C. Generated by
# `uv run compute`; overwritten on each compute. Safe to delete.
set -euo pipefail
proj="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
skill="$HOME/.aschneer/skills/personal_skills/schedule"
( cd "$skill" && uv run compute "$proj/{schedule_filename}" )
